name = "hs-address-autocomplete"
main = "worker.js"
compatibility_date = "2023-12-01"

# Enable variable bindings
usage_model = "bundled"

# Add environment variables (placeholders - configure in Cloudflare dashboard)
[vars]
# NOTE: Replace this with your actual API key in the Cloudflare dashboard
# This is just a placeholder that will be replaced in the dashboard
GOOGLE_MAPS_API_KEY = "your-google-maps-api-key-goes-here" 